description = 'A modular Hugo theme to build your next documentation site'

author = 'Dumindu Madunuwan'
authorURL = 'https://github.com/dumindu'

currentYear = 2023
projectStartYear = 2022

facebookURL = 'https://facebook.com/'
twitterURL = 'https://www.twitter.com/'
githubURL = 'https://github.com/docura/'
youtubeURL = 'https://www.youtube.com/'

githubRepo = 'docura/docura'

buyMeACoffee = 'dumindu'
githubSponsor = 'dumindu'

[algolia]
[algolia.en]
container = '#site-header-search'
appId = 'docura'
indexName = 'docura'
apiKey = ''
